[Statedef 0]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 10]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 11]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 12]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 20]

[State ]
type = SelfState
trigger1 = 1
value = 120


[Statedef 40]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 45]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 50]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 51]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 52]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 100]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 105]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 106]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 110]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 115]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 130]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 131]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 132]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 140]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 150]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 151]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 152]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 153]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 154]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 155]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 170]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 175]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 190]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 191]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5000]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5001]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5010]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5011]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5020]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5030]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5035]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5040]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5050]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5070]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5071]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5080]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5081]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5100]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5101]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5110]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5120]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5150]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5200]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5201]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5210]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5500]

[State ]
type = SelfState
trigger1 = 1
value = 120

[Statedef 5900]

[State ]
type = SelfState
trigger1 = 1
value = 120

